Vim executable: add VIM_PATH env var to choose, update defaults
* Add $VIM_PATH env var so that you can set the vim you want it to use
  (primarily for simplicity, but will also be negligibly faster)
* add /usr/local/bin/vim, which is potentially linked to some homebrew vim
* add neovim
* remove macvim_homebrew b/c its path changes across versions,
  and doing an ls with a wildcard leads to errors. Could potentially also do
  some logic to check the dir before doing the ls there, but whatever, I'm
  not currently using it, and don't feel like having it execute unnecessary
  syscalls each time I start up.

diff --git a/bin/vim b/bin/vim
--- a/bin/vim
+++ b/bin/vim
@@ -1,14 +1,25 @@
 #!/bin/sh
 
-macvim_app="/Applications/MacVim.app/Contents/MacOS/Vim" # get it with `brew install macvim && brew linkapps`
-macvim_homebrew="$(ls "/usr/local/Cellar/macvim/"*"/MacVim.app/Contents/bin/vim" | tail -1)"
+# get it with `brew install macvim && brew linkapps`
+macvim_app="/Applications/MacVim.app/Contents/MacOS/Vim"
+brew_vim="/usr/local/bin/vim" # could be anything, really
+nvim="/usr/local/bin/nvim"
 systemvim="/usr/bin/vim"
 selectedvim=""
 
-if test -e "$macvim_app"; then
+if test -n "$VIM_PATH"; then
+  if test -e "$VIM_PATH"; then
+    selectedvim="$VIM_PATH"
+  else
+    echo "\$VIM_PATH is set to $VIM_PATH, but could not find that executable" >&2
+    exit 1
+  fi
+elif test -e "$macvim_app"; then
   selectedvim="$macvim_app"
-elif test -e "$macvim_homebrew"; then
-  selectedvim="$macvim_homebrew"
+elif test -e "$brew_vim"; then
+  selectedvim="$brew_vim"
+elif test -e "$nvim"; then
+  selectedvim="$nvim"
 elif test -e "$systemvim"; then
   selectedvim="$systemvim"
 else
